namespace Nancy.Demo.Hosting.Aspnet
{
    using Nancy.ErrorHandling;

    public class CustomErrorHandler : IErrorHandler
    {
        /// <summary>
        /// Whether then 
        /// </summary>
        /// <param name="statusCode">Status code</param>
        /// <returns>True if handled, false otherwise</returns>
        public bool HandlesStatusCode(HttpStatusCode statusCode)
        {
            return statusCode == HttpStatusCode.ImATeapot;
        }

        /// <summary>
        /// Handle the error code
        /// </summary>
        /// <param name="statusCode">Status code</param>
        /// <param name="context">Current context</param>
        public void Handle(HttpStatusCode statusCode, NancyContext context)
        {
            context.Response = "Response generated by a custom error handler";
        }
    }
}